version: "3.0"

services:
  api:
    container_name: "api"
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./app:/src

  postgres:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
  volume_pgadmin: